import type { GameDefinition } from "../types";

/* Minecraft: Java Edition.

   The image installs and updates the server itself; which server it
   installs is a matter of two environment variables, which is why each
   version carries TYPE and VERSION rather than a tag of its own. Without
   them every version in the list would produce the same server. */

export const MINECRAFT_JAVA: GameDefinition = {
  id: "minecraft-java",
  name: "Minecraft: Java Edition",
  family: "Minecraft",
  art: "MC\nJAVA",
  official: true,
  popularity: "2.1M servers",
  blurb: "Paper, Purpur, Fabric, Forge and vanilla. The whole modded ecosystem.",

  portBase: 25565,
  portSpan: 400,
  ports: [
    { id: "game", label: "Game", offset: 0, protocol: "both", primary: true },
    { id: "query", label: "Query", offset: 1, protocol: "udp" },
    {
      id: "rcon",
      label: "RCON",
      offset: 2,
      protocol: "tcp",
      container: 25575,
      public: false,
      note: "private",
    },
  ],

  defaults: { memoryGb: 8, cpuLimit: 300, diskGb: 60, playersMax: 40 },
  limits: { memoryGb: [1, 32], cpuLimit: [50, 800], diskGb: [5, 250] },
  requirements: {
    memoryGbMin: 1,
    cpuPctMin: 50,
    diskGbMin: 5,
    os: ["linux"],
    arch: ["x64", "arm64"],
    capabilities: ["docker", "java"],
  },

  install: {
    kind: "image",
    /* The image refuses to start without this, and it is not a setting:
       there is no server to run if it is false. */
    env: { EULA: "TRUE" },
  },

  config: [
    {
      key: "motd",
      label: "MOTD",
      type: "string",
      target: { kind: "env", name: "MOTD" },
      default: "A Geeboard server",
      maxLength: 120,
      group: "Presentation",
      help: "The line shown under the server name in a player's list.",
      restartRequired: true,
    },
    {
      key: "mode",
      label: "Game mode",
      type: "enum",
      target: { kind: "env", name: "MODE" },
      default: "survival",
      options: [
        { value: "survival", label: "Survival" },
        { value: "creative", label: "Creative" },
        { value: "adventure", label: "Adventure" },
        { value: "spectator", label: "Spectator" },
      ],
      group: "World",
    },
    {
      key: "difficulty",
      label: "Difficulty",
      type: "enum",
      target: { kind: "env", name: "DIFFICULTY" },
      default: "normal",
      options: [
        { value: "peaceful", label: "Peaceful" },
        { value: "easy", label: "Easy" },
        { value: "normal", label: "Normal" },
        { value: "hard", label: "Hard" },
      ],
      group: "World",
    },
    {
      key: "hardcore",
      label: "Hardcore",
      type: "boolean",
      target: { kind: "env", name: "HARDCORE" },
      default: false,
      group: "World",
      help: "One life each. Death moves a player to spectator.",
      restartRequired: true,
    },
    {
      key: "seed",
      label: "World seed",
      type: "string",
      target: { kind: "env", name: "SEED" },
      default: "",
      maxLength: 64,
      group: "World",
      help: "Only used when the world is generated. Changing it later does nothing.",
      restartRequired: true,
      advanced: true,
    },
    {
      key: "maxPlayers",
      label: "Max players",
      type: "number",
      target: { kind: "env", name: "MAX_PLAYERS" },
      default: 40,
      min: 1,
      max: 500,
      group: "Players",
    },
    {
      key: "pvp",
      label: "PvP",
      type: "boolean",
      target: { kind: "env", name: "PVP" },
      default: true,
      group: "Players",
    },
    {
      key: "whitelist",
      label: "Whitelist only",
      type: "boolean",
      target: { kind: "env", name: "ENABLE_WHITELIST" },
      default: false,
      group: "Players",
      help: "Only listed players can join.",
    },
    {
      key: "onlineMode",
      label: "Verify accounts",
      type: "boolean",
      target: { kind: "env", name: "ONLINE_MODE" },
      default: true,
      group: "Players",
      help: "Turning this off lets anyone join under any name. Leave it on unless a proxy is doing the checking.",
      advanced: true,
      restartRequired: true,
    },
    {
      key: "viewDistance",
      label: "View distance",
      type: "number",
      target: { kind: "env", name: "VIEW_DISTANCE" },
      default: 10,
      min: 3,
      max: 32,
      group: "Performance",
      help: "Chunks. Each step costs memory and CPU on every player.",
      restartRequired: true,
    },
    {
      key: "spawnProtection",
      label: "Spawn protection",
      type: "number",
      target: { kind: "env", name: "SPAWN_PROTECTION" },
      default: 16,
      min: 0,
      max: 256,
      group: "World",
      advanced: true,
    },
    {
      key: "keepInventory",
      label: "Keep inventory on death",
      type: "boolean",
      target: { kind: "env", name: "KEEP_INVENTORY" },
      default: false,
      group: "World",
      advanced: true,
    },
  ],

  health: {
    probes: [
      { kind: "port", port: "game" },
      { kind: "query", protocol: "minecraft-ping" },
    ],
    bootGraceSeconds: 180,
    readyPattern: 'Done \\([\\d.]+s\\)! For help',
    crashPattern: "(java\\.lang\\.OutOfMemoryError|Exception in server tick loop)",
  },

  console: {
    stopCommand: "stop",
    saveCommand: "save-all",
    broadcastCommand: "say %s",
    examples: ["list", "whitelist add <player>", "op <player>", "time set day", "save-all"],
  },

  versionSources: [{ provider: "static" }, { provider: "minecraft-launcher" }],

  versions: [
    {
      id: "paper-1-21-4",
      label: "Paper 1.21.4",
      upstream: "1.21.4",
      image: "itzg/minecraft-server:java21",
      env: { TYPE: "PAPER", VERSION: "1.21.4" },
      note: "The plugin server most people mean",
      released: "2024-12-03",
      channel: "stable",
      recommended: true,
    },
    {
      id: "purpur-1-21-4",
      label: "Purpur 1.21.4",
      upstream: "1.21.4",
      image: "itzg/minecraft-server:java21",
      env: { TYPE: "PURPUR", VERSION: "1.21.4" },
      note: "Paper with more knobs, for a PvP server that needs them",
      released: "2024-12-03",
      channel: "stable",
    },
    {
      id: "fabric-1-21-4",
      label: "Fabric 1.21.4",
      upstream: "1.21.4",
      image: "itzg/minecraft-server:java21",
      env: { TYPE: "FABRIC", VERSION: "1.21.4" },
      note: "The mod loader, when the modpack asks for it",
      released: "2024-12-03",
      channel: "stable",
    },
    {
      id: "vanilla-1-21-4",
      label: "Vanilla 1.21.4",
      upstream: "1.21.4",
      image: "itzg/minecraft-server:java21",
      env: { TYPE: "VANILLA", VERSION: "1.21.4" },
      note: "Mojang's own server, with nothing added",
      released: "2024-12-03",
      channel: "stable",
    },
    {
      id: "paper-1-20-6",
      label: "Paper 1.20.6",
      upstream: "1.20.6",
      image: "itzg/minecraft-server:java21",
      env: { TYPE: "PAPER", VERSION: "1.20.6" },
      note: "Held back for a plugin that has not caught up yet",
      released: "2024-04-29",
      channel: "legacy",
    },
  ],

  templates: [
    {
      id: "survival",
      name: "Survival",
      blurb: "The default world, with the guardrails an operator usually wants on day one.",
      summary: "Whitelist on, keep-inventory off, hard difficulty",
      whitelist: true,
      config: { mode: "survival", difficulty: "hard", whitelist: true, keepInventory: false },
    },
    {
      id: "creative",
      name: "Creative",
      blurb: "Flight and unlimited blocks, for a build server nobody has to survive.",
      summary: "Creative mode, peaceful, whitelist off",
      whitelist: false,
      config: { mode: "creative", difficulty: "peaceful", whitelist: false },
    },
    {
      id: "hardcore",
      name: "Hardcore",
      blurb: "One life each. Death puts a player into spectator rather than removing them.",
      summary: "Hardcore, hard difficulty, whitelist on",
      whitelist: true,
      config: { mode: "survival", difficulty: "hard", hardcore: true, whitelist: true },
    },
    {
      id: "minigames",
      name: "Minigames",
      blurb: "Adventure mode with a fixed spawn, for a hub that hands players off elsewhere.",
      summary: "Adventure mode, spawn protection on, PvP off",
      whitelist: false,
      config: { mode: "adventure", pvp: false, spawnProtection: 32 },
    },
  ],
};
